### ISSUE TITLE
Its just bad

### ISSUE THREAD

**Issue by parthyyy** [elajedrecista/cchess#1]
This program is really bad. i downloaded it on my laptop and i hate it. I am strongly convinced that this app is invented by Satan as every time I open it, my heart starts beating uncontrollably and my mum starts screaming. The windows all shatter and there is a terrible squealing sound coming from the plants. Black slime starts swallowing up my house and I find it hard to breathe. Swarms of mosquitos invade my house and eat my sister up. I am not able to get rid of this. Download at your own risk.

**Comment by elajedrecista** [comment]
ok elizabeth proctor

marked as duplicate
